
apiVersion: v1
kind: Secret
metadata:
  name: dootask-secret
type: Opaque
stringData:
  DB_USERNAME: "dootask"
  DB_PASSWORD: "$DB_PASSWORD"
  DB_ROOT_PASSWORD: "$DB_ROOT_PASSWORD"
  APP_KEY: "$APP_KEY"
  DB_HOST: "dootask-mariadb"
  DB_PORT: "3306"
  DB_DATABASE: "dootask"
  DB_PREFIX: "pre_"
  REDIS_HOST: "dootask-redis"
  REDIS_PORT: "6379"
  TIMEZONE: "PRC"
