apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-nginx-speedbox-web
  labels:
    app: web-nginx-speedbox-web
spec:
  replicas: 1  # 可以根据需要调整副本数量
  selector:
    matchLabels:
      app: web-nginx-speedbox-web
  template:
    metadata:
      labels:
        app: web-nginx-speedbox-web
    spec:
      containers:
      - name: nginx
        image: hub.hitosea.com/speedbox/speedbox-web:1.0.1
        ports:
        - containerPort: 80
        # 可以在这里添加环境变量或其他配置
---
apiVersion: v1
kind: Service
metadata:
  name: web-nginx-speedbox-web
spec:
  type: ClusterIP  # 可以根据需要选择 ClusterIP 或 LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: web-nginx-speedbox-web