apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflank-config
data:
  Caddyfile: |
    cloudflank.keli.vip {
          
            handle /api/verify-turnstile {
                    reverse_proxy http://app:3000
            }
            handle /api/proxy-form {
                    reverse_proxy http://app:3000
            }
            handle /api/* {
                    reverse_proxy 103.63.139.238 {
                            header_up X-Real-IP {remote}
                            header_up X-Forwarded-Proto {scheme}
                            header_up X-Forwarded-For {host}
                            header_up Host {host}
                    }
            }
            handle /uploads/* {
                    reverse_proxy 103.63.139.238 {
                            header_up X-Real-IP {remote}
                            header_up X-Forwarded-Proto {scheme}
                            header_up X-Forwarded-For {host}
                            header_up Host {host}
                    }
            }
            reverse_proxy http://app:3000
    }
