apiVersion: batch/v1
kind: Job
metadata:
  name: likeshop-init-job
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      initContainers:
      - name: wait-for-mysql
        image: mysql:8.0
        command: ['sh', '-c']
        args:
          - |

            echo "Waiting for MySQL to be ready..."
            until mysql -h likeshop-mariadb -u$(printenv DB_USERNAME) -p$(printenv DB_PASSWORD) -e "SELECT 1" >/dev/null 2>&1; do
              echo "MySQL is unavailable - sleeping"
              sleep 2
            done
            
            # 尝试创建数据库
            mysql -h likeshop-mariadb -u$(printenv DB_USERNAME) -p$(printenv DB_PASSWORD) -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
            
            echo "MySQL is up and ready!"
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_DATABASE
      containers:
      - name: init
        image: hitosea2020/php-fpm:1.0.6
        command: ["/bin/sh", "-c"]
        args:
          - |
            cd /usr/src
            rm -f .success

            if [ ! -d "likeshop" ]; then
                git clone -b $BRANCH https://$GIT_TOKEN@github.com/innet8/likeshop.git 
            else
                cd likeshop/
                git pull
            fi
           
            echo "Preparation completed successfully" > .success
        env:
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD
        volumeMounts:
        - name: likeshop-php-data
          mountPath: /usr/src

      volumes:
      - name: likeshop-php-data
        persistentVolumeClaim:
          claimName: php-pvc

      restartPolicy: OnFailure
