apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  DB_USERNAME: "likeadmin"
  DB_PASSWORD: "bf883b664e38721b"
  DB_ROOT_PASSWORD: "bf883b664e38721b"
  DB_DATABASE: "likeadmin"
  REDIS_HOST: "likeshop-redis"
  REDIS_PORT: "6479"
  