
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_HOST: "jjjshop-mariadb"
  DB_PORT: "3306"
  DB_DATABASE: "saas"
  DB_USERNAME: jjj
  DB_PREFIX: "jjjfood_"
  REDIS_HOST: "jjjshop-redis"
  REDIS_PORT: "6379"
  TIMEZONE: "PRC"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    include /etc/nginx/conf.d/conf.d/*.http;

    #这里的IP是代理服务器的IP，也可以是IP段。意思是把该IP请求过来的x_forwarded_for设为remote_addr
    set_real_ip_from 10.0.0.0/24;
    set_real_ip_from 192.168.0.0/16;
    set_real_ip_from 172.16.0.0/12;
    real_ip_header X-Forwarded-For;

    # 上传限制
    client_max_body_size 120m;
    client_header_buffer_size 100k;

    # websock
    upstream ws_services {
        server php:2345 weight=5 max_fails=3 fail_timeout=30s;
        keepalive 16;
    }

    # 设置图片缓存目录
    proxy_cache_path /var/cache/imgs levels=1:2 keys_zone=my_cache_c:2m;  

    # 
    server {
        listen 80;
        server_name localhost;
        include /etc/nginx/conf.d/conf.d/*.conf;
        root /var/www/public;
        index index.html index.htm;

        location ~ ^/(admin|cashier|apidoc|shop|kitchen|tablet|scan|assistant|menu)$ {
            return 301 $scheme://$http_host$request_uri/;
        }

        location ~ ^/(admin|cashier/|apidoc/|shop/|kitchen/|tablet/|scan/|assistant/|menu/) {
            index index.html;
            if ($uri ~* \.html) {
                add_header Content-Type "text/html; charset=utf-8";
            }
        }
        
        location /index.php {
            rewrite ^/index.php/(.*)$ /index.php?s=/$1 last;
        }

        location /api {
            rewrite ^/api/(.*)$ /index.php?s=/$1 last;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass php:9000;
            fastcgi_index index.php/admin;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location /ws {
            proxy_http_version 1.1;
        proxy_connect_timeout 180s;
            proxy_send_timeout 1600s;
            proxy_read_timeout 1600s;
            proxy_set_header X-Real-IP $http_x_forwarded_for;
            proxy_set_header X-Real-PORT $remote_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header Scheme $scheme;
            proxy_set_header Server-Protocol $server_protocol;
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_404;
            proxy_max_temp_file_size 128m;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";	
            proxy_pass http://ws_services;
      }

        location ~ ^/api/product/thumb.*\.(gif|jpg|jpeg|png)$ {
            proxy_cache my_cache_c;
            proxy_cache_key "$scheme$request_method$host$request_uri";
            add_header Nginx-Cache-Status "$upstream_cache_status";
            proxy_cache_valid 200 301 302 7d;
            # 
            proxy_http_version 1.1;
            proxy_set_header Connection "Upgrade";  
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Real-PORT $remote_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header Scheme $scheme;
            proxy_set_header Server-Protocol $server_protocol;
            proxy_set_header Server-Name $server_name;
            proxy_set_header Server-Addr $server_addr;
            proxy_set_header Server-Port $server_port;
            proxy_pass http://nginx:30000;
        }
        
        # 代理谷歌云存储
        location /storage_googleapis/ { 
            proxy_pass https://storage.googleapis.com/;  
            proxy_set_header Host storage.googleapis.com;  # 设置 Host 头
            proxy_set_header X-Real-IP $remote_addr;  # 将真实 IP 传递给后端
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # 传递代理链中的 IP 地址
            # 告诉浏览器要缓存图片
            expires 365d;
            add_header Cache-Control "public, max-age=31536000"; 
        }

        # 导出模版
        location /imports {
            root /var/www/public/;
        }

        gzip on;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css application/x-javascript application/json application/javascript image/x-icon image/png image/gif image/jpeg image/svg+xml;
        charset utf-8;
        access_log off;
    }

    # 缓存图片用
    server {
        listen 30000;
        server_name localhost;

        root /var/www/public;
        index index.html index.htm;

        location /api {
            rewrite ^/api/(.*)$ /index.php?s=/$1 last;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass php:9000;
            fastcgi_index index.php/admin;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    worker_rlimit_nofile 65535;  
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  65536;
        multi_accept on;  # 单次事件循环中接受多个新连接
        use epoll;  # Linux 环境下使用高效的 I/O 事件通知:x

    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        proxy_cache_path /tmp/cache levels=1:2 keys_zone=my_cache:10m max_size=10g inactive=60m use_temp_path=off;


        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;



        sendfile        on;  # 启用高效文件传输
        tcp_nopush      on;  # 减少网络拥塞
        tcp_nodelay     on;  # 减少网络延迟
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;

        proxy_read_timeout 120s;
        keepalive_timeout  120;  # 连接保持时间
        client_body_timeout 120;  # 客户端请求体超时
        client_header_timeout 120;  # 客户端请求头超时
        send_timeout 120;  # 响应发送超时
        # proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m max_size=1g inactive=60m use_temp_path=off;


        gzip on;  # 启用 gzip 压缩
        gzip_disable "msie6";  # 禁用对 IE6 的 gzip
        gzip_vary on;  # 向代理服务器传递 Vary: Accept-Encoding
        gzip_proxied any;  # 允许压缩所有代理请求
        gzip_comp_level 6;  # 压缩级别
        gzip_buffers 16 8k;  # 缓冲区设置
        gzip_http_version 1.1;  # HTTP 版本
        gzip_types
            text/plain
            text/css
            application/json
            application/javascript
            text/xml
            application/xml
            application/xml+rss
            text/javascript;



        include /etc/nginx/conf.d/*.conf;
    }  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  limits.conf: |-
    * soft nofile 65535
    * hard nofile 65535
  my.conf: |-
    [mysqld]
    wait_timeout = 28800
    connect_timeout = 30

    skip-host-cache
    skip-name-resolve
    skip-external-locking

    binlog_cache_size = 256K
    thread_stack = 512K
    join_buffer_size = 8192K
    query_cache_type = 1
    max_heap_table_size = 2048M
    default_storage_engine = InnoDB
    performance_schema_max_table_instances = 400
    table_definition_cache = 400
    key_buffer_size = 1024M
    max_allowed_packet = 8192M
    table_open_cache = 2048
    sort_buffer_size = 4096K
    net_buffer_length = 4K
    read_buffer_size = 4096K
    read_rnd_buffer_size = 2048K
    myisam_sort_buffer_size = 8M
    thread_cache_size = 256
    query_cache_size = 384M
    tmp_table_size = 2048M
    sql-mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES

    max_connections = 65535
    max_connect_errors = 100
    open_files_limit = 65535

    log-bin=mysql-bin
    binlog_format=mixed
    server-id = 1
    expire_logs_days = 10
    slow_query_log=1
    slow-query-log-file=/var/lib/mysql/mysql-slow.log
    long_query_time=3

    innodb_buffer_pool_size = 4096M
    innodb_log_file_size = 64M
    innodb_log_buffer_size = 16M
    innodb_flush_log_at_trx_commit = 1
    innodb_lock_wait_timeout = 50
    innodb_max_dirty_pages_pct = 90
    innodb_read_io_threads = 2
    innodb_write_io_threads = 2

    [mysqldump]
    quick
    max_allowed_packet = 2048M

    [mysql]
    no-auto-rehash

    [myisamchk]
    key_buffer_size = 32M
    sort_buffer_size = 768K
    read_buffer = 2M
    write_buffer = 2M

    [mysqlhotcopy]
    interactive-timeout
  nginx.conf: |-

    user  nginx;
    worker_processes  auto;
    worker_rlimit_nofile 65535;  
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  65536;
        multi_accept on;  # 单次事件循环中接受多个新连接
        use epoll;  # Linux 环境下使用高效的 I/O 事件通知:x

    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        proxy_cache_path /tmp/cache levels=1:2 keys_zone=my_cache:10m max_size=10g inactive=60m use_temp_path=off;


        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;



        sendfile        on;  # 启用高效文件传输
        tcp_nopush      on;  # 减少网络拥塞
        tcp_nodelay     on;  # 减少网络延迟
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;

        proxy_read_timeout 120s;
        keepalive_timeout  120;  # 连接保持时间
        client_body_timeout 120;  # 客户端请求体超时
        client_header_timeout 120;  # 客户端请求头超时
        send_timeout 120;  # 响应发送超时
        proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m max_size=1g inactive=60m use_temp_path=off;


        gzip on;  # 启用 gzip 压缩
        gzip_disable "msie6";  # 禁用对 IE6 的 gzip
        gzip_vary on;  # 向代理服务器传递 Vary: Accept-Encoding
        gzip_proxied any;  # 允许压缩所有代理请求
        gzip_comp_level 6;  # 压缩级别
        gzip_buffers 16 8k;  # 缓冲区设置
        gzip_http_version 1.1;  # HTTP 版本
        gzip_types
            text/plain
            text/css
            application/json
            application/javascript
            text/xml
            application/xml
            application/xml+rss
            text/javascript;



        include /etc/nginx/conf.d/*.conf;
    }
  php.ini: |-
    [PHP]
    engine = On
    short_open_tag = Off
    precision = 14
    output_buffering = 4096
    zlib.output_compression = Off
    implicit_flush = Off
    unserialize_callback_func =
    serialize_precision = -1
    disable_functions =
    disable_classes =
    zend.enable_gc = On
    zend.exception_ignore_args = On
    zend.exception_string_param_max_len = 0
    expose_php = On
    max_execution_time = 30
    max_input_time = 60
    max_input_vars = 1000000
    memory_limit = 512M
    error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
    display_errors = Off
    display_startup_errors = Off
    log_errors = On
    ignore_repeated_errors = Off
    ignore_repeated_source = Off
    report_memleaks = On
    variables_order = "GPCS"
    request_order = "GP"
    register_argc_argv = Off
    auto_globals_jit = On
    post_max_size = 8M
    auto_prepend_file =
    auto_append_file =
    default_mimetype = "text/html"
    default_charset = "UTF-8"
    doc_root =
    user_dir =
    enable_dl = Off
    file_uploads = On
    upload_max_filesize = 2M
    max_file_uploads = 20
    allow_url_fopen = On
    allow_url_include = Off
    default_socket_timeout = 60
    [CLI Server]
    cli_server.color = On
    [Date]
    [filter]
    [iconv]
    [imap]
    [intl]
    [sqlite3]
    [Pcre]
    [Pdo]
    [Pdo_mysql]
    pdo_mysql.default_socket=
    pdo_mysql.cache_size = 2000 
    [Phar]
    [mail function]
    SMTP = localhost
    smtp_port = 25
    mail.add_x_header = Off
    [ODBC]
    odbc.allow_persistent = On
    odbc.check_persistent = On
    odbc.max_persistent = -1
    odbc.max_links = -1
    odbc.defaultlrl = 4096
    odbc.defaultbinmode = 1
    [MySQLi]
    mysqli.cache_size = 2000
    mysqli.max_persistent = -1
    mysqli.allow_persistent = On
    mysqli.max_links = -1
    mysqli.default_port = 3306
    mysqli.default_socket =
    mysqli.default_host =
    mysqli.default_user =
    mysqli.default_pw =
    mysqli.reconnect = Off
    [mysqlnd]
    mysqlnd.collect_statistics = On
    mysqlnd.collect_memory_statistics = Off
    [OCI8]
    [PostgreSQL]
    pgsql.allow_persistent = On
    pgsql.auto_reset_persistent = Off
    pgsql.max_persistent = -1
    pgsql.max_links = -1
    pgsql.ignore_notice = 0
    pgsql.log_notice = 0
    [bcmath]
    bcmath.scale = 0
    [browscap]
    [Session]
    session.save_handler = files
    session.use_strict_mode = 0
    session.use_cookies = 1
    session.use_only_cookies = 1
    session.name = PHPSESSID
    session.auto_start = 0
    session.cookie_lifetime = 0
    session.cookie_path = /
    session.cookie_domain =
    session.cookie_httponly =
    session.cookie_samesite =
    session.serialize_handler = php
    session.gc_probability = 1
    session.gc_divisor = 1000
    session.gc_maxlifetime = 1440
    session.referer_check =
    session.cache_limiter = nocache
    session.cache_expire = 180
    session.use_trans_sid = 0
    session.sid_length = 26
    session.trans_sid_tags = "a=href,area=href,frame=src,form="
    session.sid_bits_per_character = 5
    [Assertion]
    zend.assertions = -1
    [COM]
    [mbstring]
    [gd]
    [exif]
    [Tidy]
    tidy.clean_output = Off
    [soap]
    soap.wsdl_cache_enabled=1
    soap.wsdl_cache_dir="/tmp"
    soap.wsdl_cache_ttl=86400
    soap.wsdl_cache_limit = 5
    [sysvshm]
    [ldap]
    ldap.max_links = -1
    [dba]
    [opcache]
    [curl]
    [openssl]
    [ffi]
    ffi.enable=true
  sysctl.conf: |-
    # 文件描述符限制
    fs.file-max = 1000000

    # 增大 TCP 缓冲区大小
    net.core.rmem_max = 16777216
    net.core.wmem_max = 16777216
    net.ipv4.tcp_rmem = 4096 87380 16777216
    net.ipv4.tcp_wmem = 4096 65536 16777216

    # 增大监听队列和 SYN 队列长度
    net.core.somaxconn = 65535
    net.ipv4.tcp_max_syn_backlog = 8192

    # 启用 TIME-WAIT 复用
    net.ipv4.tcp_tw_reuse = 1

    # 增大本地端口范围
    net.ipv4.ip_local_port_range = 1024 65535

    # 增大共享内存限制
    kernel.shmmax = 68719476736
    kernel.shmall = 4294967296

    # 调整 TCP 缓存
    net.ipv4.tcp_mem = 50576 64768 98152

    # 启用 TCP 快速打开
    net.ipv4.tcp_fastopen = 3

    # 启用 SYN Cookies 以防止 SYN 洪水攻击
    net.ipv4.tcp_syncookies = 1
  www.conf: |-
    [www]
    user = www-data
    group = www-data
    listen = 127.0.0.1:9000
    listen.mode = 0666
    pm = Static
    pm.max_children = 50
    pm.start_servers = 50
    pm.min_spare_servers = 50
    pm.max_spare_servers = 50
    pm.process_idle_timeout = 10s;
    pm.max_requests = 65535
    request_terminate_timeout = 60s
    catch_workers_output = yes
    clear_env = no
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  .env: |
    APP_ID=k8stest
    APP_IPPR=127.0.0.1
    APP_DEBUG=false
    APP_PORT=80
    APP_SSL_PORT=
    DEFAULT_TIMEZONE=Asia/Shanghai
    CACHE_DRIVER=redis
    TOKEN_SALT="@#$%*&fasw-dkjhs.fd"

    # 数据库
    DB_TYPE=mysql
    DB_HOST=jjjshop-mariadb
    DB_PREFIX=jjjfood_
    DB_DATABASE=saas
    DB_USERNAME=root
    DB_PORT=3306
    DB_PASSWORD=bf883b664e38721b
    DB_ROOT_PASSWORD=bf883b664e38721b

    # REDIS
    REDIS_HOST=redis
    REDIS_PORT=6379
    REDIS_PASSWORD=

    # RABBITMQ
    RABBITMQ_HOST=rabbitmq
    RABBITMQ_PORT=5672
    RABBITMQ_USER=${APP_ID}
    RABBITMQ_PASSWORD=${DB_ROOT_PASSWORD}

    # 有道翻译
    YOUDAO_APP_KEY=
    YOUDAO_SEC_KEY=

    # 是否是云上部署
    IS_CLOUD_DEPLOY=true
    # 打印机数量
    CLOUD_PRINTER_NUM=1
    # 桌台数量
    CLOUD_TABLE_NUM=5

    # 云平台的地址
    CLOUD_PLATFORM_HOST=http://nginx

    # 支付服务
    PAY_SERVICE_AUTH_URI=/api/platform/add
    PAY_SERVICE_URL=http://103.63.139.152:4477
    PAY_SERVICE_IP=103.63.139.152
    PAY_SERVICE_RSA_PUBLIC_KEY=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDAw6W//ZNMzCrX96v+eTIbuU3UsjmVLTf45Waj5rb3MALGOWLeQzeTciy0mIMnKWcN70Yl4ofU+884U8ihTqlTYlosBcschKAfFkLJXeQWmFL3GlNy/IzMgGtxlmn03H7IGphCKvsUBFYlXjdAB5znm3WcvGL/+/hPt+83IT9E6wIDAQAB
    PAY_SERVICE_LIANLIAN_CALLBACK_URL=https://jjjshop.keli.vip/index.php/cashier/payment.callback/lianlianCallback
    PAY_SERVICE_LIANLIAN_REFUND_CALLBACK_URL=https://jjjshop.keli.vip/index.php/cashier/payment.callback/lianlianRefundCallback
    #模拟lianlianpay 支付退款失败
    #PAY_SERVICE_URL=http://baidu.com 

    DB_PORT_OPEN=33070


    # 谷歌云证书文件名
    GOOGLE_APPLICATION_CREDENTIALS_FILE_NAME=diyl-407103-c906df6d2baa.json
    # 谷歌云bucket
    GOOGLE_APPLICATION_BUCKET_NAME=dc_apk
    # 谷歌云bucket - 安装包 - 环境
    GOOGLE_APPLICATION_BUCKET_ENV=Test
    # 谷歌云- 上传图片的bucket目录名称 （diacan-test）
    GOOGLE_APPLICATION_UPLOADS_BUCKET_NAME=diacan-test
    # 谷歌云 - 上传图片的目录名称 （TTPOS-Test）
    GOOGLE_APPLICATION_UPLOADS_CATALOGUE_NAME=TTPOS-Test
  GOOGLE_APPLICATION_CREDENTIALS_FILE: |
    {
      "type": "service_account",
      "project_id": "diyl-407103",
      "private_key_id": "c906df6d2baa",
      "private_key": "-----
    }