apiVersion: batch/v1
kind: Job
metadata:
  name: jjjshop-init-job
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      initContainers:
      - name: wait-for-mysql
        image: mysql:8.0
        command: ['sh', '-c']
        args:
          - |

            echo "Waiting for MySQL to be ready..."
            until mysql -h jjjshop-mariadb -u$(printenv DB_USERNAME) -p$(printenv DB_PASSWORD) -e "SELECT 1" >/dev/null 2>&1; do
              echo "MySQL is unavailable - sleeping"
              sleep 2
            done
            
            # 尝试创建数据库
            mysql -h jjjshop-mariadb -u$(printenv DB_USERNAME) -p$(printenv DB_PASSWORD) -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
            
            echo "MySQL is up and ready!"
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_DATABASE
      containers:
      - name: init
        image: hitosea2020/php-fpm:1.0.6
        command: ["/bin/sh", "-c"]
        args:
          - |
            cd /var/www
            rm -f .success

            if [ ! -d ".git" ]; then
                git clone -b $BRANCH https://$GIT_TOKEN@github.com/innet8/jjjshop.git 
                cd jjjshop/jjj_food_chain/
                export COMPOSER_ALLOW_SUPERUSER=1
                composer install --ignore-platform-reqs
            else
                cd jjjshop/
                git pull
                cd jjj_food_chain/
                export COMPOSER_ALLOW_SUPERUSER=1
                composer update --ignore-platform-reqs
            fi
            php think migrate:run
            php think clear-cache
            php think get-mac-addr
            php think renewal:info
            
            chown -R www-data:www-data ./app
            chown -R www-data:www-data ./public
            chown -R www-data:www-data ./runtime
            chown -R www-data:www-data ./extend
            chown -R www-data:www-data ./vendor
            chown -R www-data:www-data ./route
            chown -R www-data:www-data ./bin
            chown -R www-data:www-data think
            chmod +x ./bin/license.so
            chmod +x ./bin/license_arm.so

            echo "Preparation completed successfully" > .success
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD
        - name: DB_PREFIX
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PREFIX
        volumeMounts:
        - name: jjjshop-php-data
          mountPath: /var/www

      volumes:
      - name: jjjshop-php-data
        persistentVolumeClaim:
          claimName: jjjshop-php-pvc

      restartPolicy: OnFailure
