apiVersion: apps/v1
kind: Deployment
metadata:
  name: jjjshop-redis
spec:
  selector:
    matchLabels:
      app: jjjshop-redis
  template:
    metadata:
      labels:
        app: jjjshop-redis
    spec:
      containers:
      - name: redis
        image: redis:6
        command: ["redis-server", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jjjshop-redis
spec:
  selector:
    app: jjjshop-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379