apiVersion: v1
kind: Service
metadata:
  name: crm-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: dolibarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: {{ .Release.Namespace }}

spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app.kubernetes.io/name: mariadb-galera
  type: ClusterIP
