pipeline {
  agent {
    node {
      label 'base'
    }

  }
  stages {
    stage('clone code') {
      steps {
        container('nodejs') {
          git(url: 'https://github.com/innet8/devops-k8s-deploy.git', credentialsId: '<no value>', branch: 'main', changelog: true, poll: false)
        }

      }
    }

    stage('deploy to dev') {
      agent none
      steps {
        container('base') {
          input(id: 'deploy-to-dev', message: 'deploy to dev?')
          withCredentials([kubeconfigContent(credentialsId: 'k8s', variable: 'KUBECONFIG_CONFIG')]) {
            sh 'mkdir -p ~/.kube/'
            sh 'echo "$KUBECONFIG_CONFIG" > ~/.kube/config'
            sh '''envsubst < line-bot-webhook/deploy/deploy.yaml| kubectl -n $ENV apply -f - ;'''
          }

        }

      }
    }

  }
  environment {
    LINE_CHANNEL_SECRET = "$params.LINE_CHANNEL_SECRET"
    LINE_CHANNEL_ACCESS_TOKEN = "$params.LINE_CHANNEL_ACCESS_TOKEN"
    ENV = "$params.ENV"
  }
  parameters {
    string(name: 'LINE_CHANNEL_SECRET', defaultValue: '', description: '')
    string(name: 'LINE_CHANNEL_ACCESS_TOKEN', defaultValue: '', description: '')
    string(name: 'ENV', defaultValue: 'line-bot-webhook', description: '')

  }
}