apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  dootask.conf: |
    server {
    listen 80;

    root /var/www/public;

    client_max_body_size 1024M;

    autoindex off;
    index index.html index.htm index.php;

    charset utf-8;

    # 将 /site/* 的请求进行 301 重定向到根路径
    location /site/ {
    rewrite ^/site/(.*)$ /$1 permanent; # 使用永久重定向
    }

    # 将所有 /uploads/* 请求重定向到新域名的相同路径
    location /uploads/ {
    rewrite ^/uploads/(.*)$ https://demo1.dootask.com/uploads/$1 permanent; # 永久重定向
    }

    # 将 /manage/dashboard 重定向到新域名
    location /manage/dashboard {
    return 301 https://demo1.dootask.com/manage/dashboard;
    }

    # 将 /login 重定向到新域名
    location /login {
    return 301 https://demo1.dootask.com/login;
    }

    # 错误页面配置
    error_page 404 /404.html; # 404 错误时显示 /404.html 页面
    location = /404.html {
    root /var/www/public; # 错误页面的位置
    internal; # 只能由 Nginx 内部访问，防止直接访问
    }
    }
