kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: www.dootask.com
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - www.dootask.com
      secretName: dootask.com
  rules:
    - host: www.dootask.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dootask-web
                port:
                  number: 80