apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant-test
spec:
  mariaDbRef:
    name: mariadb-repl
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
  database: "*"
  table: "*"
  username: test
  grantOption: true
  host: "%"