
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-repl
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  storage:
    storageClassName: hitosea-rbd-sc
    size: 10Gi
    volumeClaimTemplate:
      storageClassName: hitosea-rbd-sc
  replicas: 3

  replication:
    enabled: true

  service:
    type: ClusterIP

  primaryService:
    type: ClusterIP

  secondaryService:
    type: ClusterIP

  metrics:
    enabled: true