
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-repl
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  username: mariadb
  passwordSecretKeyRef:
    name: mariadb
    key: password
  database: mariadb

  storage:
    storageClassName: hitosea-rbd-sc
    size: 10Gi
    volumeClaimTemplate:
      storageClassName: hitosea-rbd-sc
  replicas: 3

  replication:
    enabled: true

  service:
    type: ClusterIP

  primaryService:
    type: ClusterIP

  secondaryService:
    type: ClusterIP

  metrics:
    enabled: true

maxScale:
    enabled: true

    kubernetesService:
      type: ClusterIP

    guiKubernetesService:
      type: ClusterIP

    connection:
      secretName: mxs-repl-conn
      port: 3306
  
    metrics:
      enabled: true
