
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        # listen 443 ssl;
        server_name www.likeadmin.localhost;
        # ssl_certificate /ssl/www.likeadmin.localhost.crt;
        # ssl_certificate_key /ssl/www.localhost.key;
        # access_log /logs/demo.likeadmin.cnt_access_nginx.log;
        # error_log /logs/demo.likeadmin.cn_error_nginx.log;
        client_max_body_size 5M;

        location / {
            root /var/www/html/server/public; # 入口文件目录
            index index.html index.htm index.php;
            if (!-e $request_filename) {
                rewrite ^/(.*)$ /index.php?s=$1 last;
                break;
            }
        }

        location ~ /.*\.php/ {
            rewrite ^(.*?/?)(.*\.php)(.*)$ /$2?s=$3 last;
            break;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /var/www/html;
        }

        location ~ \.php$ {
            fastcgi_pass php:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME /var/www/html/server/public$fastcgi_script_name; # 入口文件目录
            include fastcgi_params;
        }

        location = /favicon.ico {
            log_not_found off;
            access_log off;
        }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: hub.hitosea.com/likeshop/nginx:v0.0.1
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  - port: 443
    targetPort: 443
  selector:
    app: nginx