apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ttpos-hls-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi  # 根据需要修改存储大小
  storageClassName: csi-cephfs-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttpos-hls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttpos-hls
  template:
    metadata:
      labels:
        app: ttpos-hls
    spec:
      containers:
      - name: hls-prod
        image: hub.hitosea.com/ttpos-web/ttpos-website-hls:1.3.2-prod
        ports:
        - containerPort: 9696
        volumeMounts:
        - name: hls-storage
          mountPath: /app/tmp  # 根据需要修改挂载路径
        env:
        - name: STRAPI_BASE_URL
          value: "https://ttpos.com"
        - name: DOOTASK_BOT_BASE_URL
          value: "https://t.hitosea.com/api/dialog/msg/sendtext"
        - name: DOOTASK_BOT_TOKEN        
          valueFrom:
            secretKeyRef:
              name: dootask-bot  # 替换为你的 Secret 名称
              key: token   # 替换为你在 Secret 中的键名
        - name: DOOTASK_BOT_DIALOG_ID
          value: "24196"
        - name: DOOTASK_BOT_VERSION
          value: "0.40.78"
      volumes:
      - name: hls-storage
        persistentVolumeClaim:
          claimName: ttpos-hls-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ttpos-hls
spec:
  type: ClusterIP
  ports:
  - port: 9696
    targetPort: 9696
  selector:
    app: ttpos-hls
