apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
  namespace: filebrowser
data:
  config.json: |
    {
      "address": "0.0.0.0",
      "port": 8080,
      "database": "/database/filebrowser.db",
      "log": "stdout",
      "locale": "zh-cn",
      "username": "admin",
      "password": "admin", 
      "root": "/srv",
      "baseURL": ""
    }
  default.conf: |
    server {
        listen 80;
        location / {
            proxy_pass http://filebrowser-service;
            # 可选：添加常用代理头配置
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        # 处理以/axure/开头的请求
        location /axure/ {
            # 将路径映射到/var/www目录下对应名称的子目录
            alias /var/www/;
            # 自动寻找索引文件（如index.html）
            index index.html index.htm;
            # 确保路径存在性检查
            try_files $uri $uri/ =404;
        }
    }