apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser:v2.32.0-s6
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config
            mountPath: /config/settings.json
            subPath: config.json
          - name: storage-volume
            mountPath: /database
            subPath: database
          - name: storage-volume
            mountPath: /srv
            subPath: srv

      volumes:
      - name: config
        configMap:
          name: filebrowser-config
      - name: storage-volume
        persistentVolumeClaim:
          claimName: filebrowser-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser-service
spec:
  selector:
    app: filebrowser
  ports:
    - port: 80
      targetPort: 8080
