apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser-nginx
  template:
    metadata:
      labels:
        app: filebrowser-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
          - name: filebrowser-data
            mountPath: /var/www/
            subPath: srv
          - name: config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf  # 挂载 default.conf
      volumes:
      - name: config
        configMap:
          name: filebrowser-config
      - name: filebrowser-data
        persistentVolumeClaim:
          claimName: filebrowser-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser-nginx
spec:
  type: ClusterIP
  selector:
    app: filebrowser-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80