apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: maxscale-repl-client
  namespace: hitosea-k8s
spec:
  mariaDbRef:
    name: mariadb-repl
    namespace: hitosea-k8s
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "DELETE"
  database: "*"
  table: "*"
  username: maxscale-repl-client
  grantOption: false
  host: "%" 
  retryInterval: 5s