apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: maxscale-repl-sync
  namespace: hitosea-k8s
spec:
  mariaDbRef:
    name: mariadb-repl
    namespace: hitosea-k8s
  passwordSecretKeyRef:
    name: maxscale
    key: password
  maxUserConnections: 20
  host: "%" 
  retryInterval: 5s