apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: maxscale-repl-sync
  namespace: hitosea-k8s
spec:
  mariaDbRef:
    name: mariadb-repl
    namespace: hitosea-k8s
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "CREATE"
    - "DROP"
  database: "mysql"
  table: "maxscale_config"
  username: maxscale-repl-sync
  grantOption: false
  host: "%" 
  retryInterval: 5s